# analysis_options.yaml
include: package:flutter/analysis_options.yaml

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    unnecessary_getters_setters: warning
    unnecessary_new: warning
    unnecessary_this: warning
    prefer_single_quotes: warning
    prefer_const_constructors: warning
    prefer_final_fields: warning
    prefer_is_empty: warning
    prefer_is_not_empty: warning
    prefer_typing_uninitialized_variables: warning

linter:
  rules:
    - avoid_print
    - always_declare_return_types
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - prefer_collection_literals
    - prefer_const_literals_to_create_immutables
    - prefer_final_locals
    - prefer_inlined_adds
    - unnecessary_const
    - unnecessary_lambdas
    - use_key_in_widget_constructors